name: Run

on:
  workflow_dispatch:
jobs:
  do-the-thing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install -y fish sqlite
      - shell: bash
        env:
          FTC_EVENTS_KEY: ${}{ secrets.FTC_EVENTS_KEY }
        run: ./retrieve-data.fish
      - run: ./process-data.fish
      - uses: actions/upload-artifact@v2
        with:
          name: ftc-data
          path: ftcdata.db
