name: Run

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  retrieve-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install -y fish
      - shell: bash
        env:
          FTC_EVENTS_KEY: ${{ secrets.FTC_EVENTS_KEY }}
        run: ./retrieve-data.fish
      - uses: actions/upload-artifact@v2
        with:
          name: data-output
          path: output
